<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.4"/>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.11" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1"/>
        <PackageReference Include="xunit" Version="2.9.3"/>
        <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="Xunit"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\src\TestTask\TestTask.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Update="TestData\valid.csv">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="TestData\10001-rows.csv">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="TestData\empty-file.csv">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="TestData\future-date.csv">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="TestData\missing-value.csv">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="TestData\negative-execution-time.csv">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="TestData\negative-value.csv">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="TestData\old-date.csv">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
        <None Update="TestData\valid2.csv">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>